name: â™Ÿï¸ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  # Check linting and formatting
  check-style:
    name: ğŸ¥¼ Check style / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-style.txt
      # Format
      - name: ğŸ§¹ Check format (ruff)
        run: |
          ruff format --check
      # Lint
      - name: âœ¨ Check lint (ruff)
        run: |
          ruff check

  # Run static type checking
  check-types:
    name: âŒ¨ï¸ Check types / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies (python)
        # Currently no dependencies ...
        run: |
          python -m pip install --upgrade pip
      # Setup node.js
      - name: ğŸ¸ Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: ğŸ“¦ Install dependencies (node.js)
        run: |
          npm install -g pyright
      # Type check
      - name: ğŸ—¿ Type check with pyright
        run: |
          pyright --verbose

  # Run tests on mac, windows, and ubuntu
  check-tests:
    name: ğŸ§ª check-tests / ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { name: ğŸ macos, os: macos-latest, python-version: "3.11" }
          - { name: ğŸ–¼ï¸ windows, os: windows-latest, python-version: "3.11" }
          - { name: ğŸ§ ubuntu, os: ubuntu-latest, python-version: "3.11" }
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Currently no dependencies ...
      - name: ğŸ› ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
      # Run tests
      - name: âš—ï¸ Run unit tests
        run: |
          python -m unittest discover -v -s tests -p test_*.py

  # Run coverage and generate artifacts
  check-coverage:
    name: ğŸ”¬ check-coverage / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-coverage.txt
      # Run tests with coverage
      - name: â˜‚ï¸ Run unittest with coverage
        run: |
          coverage run
        # Coverage html
      - name: ğŸ“Š Generate coverage html
        run: |
          coverage html
      # Upload coverage artifacts
      - name: ğŸ¤³ Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: |
            htmlcov/*
