name: â™Ÿï¸ CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  # Check linting and formatting (python)
  check-style-python:
    name: ğŸ¤µ check-style-python / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      # Format
      - name: ğŸ§¹ Check format (ruff)
        run: |
          ruff format --check
      # Lint
      - name: âœ¨ Check lint (ruff)
        run: |
          ruff check

  # Check linting and formatting (jinja)
  check-style-jinja:
    name: ğŸ±â€ğŸ‘¤ check-style-jinja / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      # Format
      - name: ğŸ§¹ Check format (djlint)
        run: |
          djlint templates -e jinja --check
      # Lint
      - name: âœ¨ Check lint (djlint)
        run: |
          djlint templates -e jinja --lint

  # Run static type checking
  check-types:
    name: âŒ¨ï¸ check-types / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    needs: check-style-python
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/leaderboard.txt
      # Setup node.js
      - name: ğŸ¸ Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: ğŸ“¦ Install dependencies (node.js)
        run: |
          npm install -g pyright
      # Type check
      - name: ğŸ—¿ Type check with pyright
        run: |
          pyright --verbose

  # Run tests on mac, windows, and ubuntu
  check-tests:
    name: ğŸ§ª check-tests / ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs:
      - check-style-jinja
      - check-types
    strategy:
      matrix:
        include:
          - { name: ğŸ§ ubuntu, os: ubuntu-latest, python-version: "3.11" }
          - { name: ğŸ–¼ï¸ windows, os: windows-latest, python-version: "3.11" }
          - { name: ğŸ macos, os: macos-latest, python-version: "3.11" }
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: ğŸ› ï¸ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/leaderboard.txt
      # Run tests
      - name: âš—ï¸ Run unit tests
        run: |
          python -m unittest discover -v -s tests -p test_*.py

  # Run coverage and generate artifacts
  check-coverage:
    name: ğŸ”¬ check-coverage / ğŸ§ ubuntu
    runs-on: ubuntu-latest
    needs: check-tests
    steps:
      # Setup
      - name: ğŸ›’ Checkout repo
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ğŸ› ï¸ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/all.txt
      # Run tests with coverage
      - name: â˜‚ï¸ Run unittest with coverage
        run: |
          coverage run
      # Coverage xml
      - name: ğŸ“œ Generate coverage xml
        run: |
          coverage xml
        # Comment about code coverage on PRs
      - name: ğŸ’ Comment coverage on PR
        if: ${{ github.event_name == 'pull_request' }}
        # Use an old version to avoid adding a check to the workflow
        uses: 5monkeys/cobertura-action@v9
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage.xml
          skip_covered: false
          minimum_coverage: 80
          show_line: true
          show_branch: true
          show_missing: true
      # Coverage html
      - name: ğŸ“Š Generate coverage html
        run: |
          coverage html
      # Upload coverage artifacts
      - name: ğŸ¤³ Upload coverage html
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: |
            htmlcov/*
